name: code_connect_frontend
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0



flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/Logo_Large.png
    - assets/images/Logo_small.png
    - assets/images/tribo_alura_conect.png
    - assets/images/codando.png
    - assets/images/simbolo_logo.png
    - assets/icons/account_circle_1.png
    - assets/icons/feed.png
    - assets/icons/info_2.png
    - assets/icons/logout_2.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt-Medium.ttf
        - asset: assets/fonts/Prompt-MediumItalic.ttf
        - asset: assets/fonts/Prompt-Regular.ttf
        - asset: assets/fonts/Prompt-Black.ttf
        - asset: assets/fonts/Prompt-BlackItalic.ttf
        - asset: assets/fonts/Prompt-bold.ttf
        - asset: assets/fonts/Prompt-boldItalic.ttf
        - asset: assets/fonts/Prompt-ExtraBold.ttf
        - asset: assets/fonts/Prompt-ExtraBoldItalic.ttf
        - asset: assets/fonts/Prompt-ExtraLight.ttf
        - asset: assets/fonts/Prompt-ExtraLightItalic.ttf
        - asset: assets/fonts/Prompt-Italic.ttf
        - asset: assets/fonts/Prompt-Light.ttf
        - asset: assets/fonts/Prompt-LightItalic.ttf
        - asset: assets/fonts/Prompt-SemiBold.ttf
        - asset: assets/fonts/Prompt-SemiBoldItalic.ttf
        - asset: assets/fonts/Prompt-Thin.ttf
        - asset: assets/fonts/Prompt-ThinItalic.ttf
  # #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
